server:
  port: 7788

spring:
  application:
    name: MY-TRAIN
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gov_train?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    druid:
      initial-size: 20
      max-active: 500
      min-idle: 20
      filter:
        stat:
          enabled: true
      stat-view-servlet:
        enabled: true
        allow: 0.0.0.0/0
  jpa:
    database: MYSQL
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
      javax.persistence.validation.mode: none
    show-sql: true
    hibernate:
      ddl-auto: update


logging:
  level:
    root: info
    # org.hibernate.SQL: debug
  pattern:
    console: ${PID} %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %-40.40logger{40}:%-5.5L - %msg%xEx%n
    file: ${PID} %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %-40.40logger{40}:%-5.5L - %msg%xEx%n
  file:
    max-history: 100
    max-size: 100MB


